Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = False
'******************************************************************************
'***     Copyright                                                                       ***
'******************************************************************************
'***    FORM:                                                                                              ***
'******************************************************************************
'***    FONCTION:                                                                                       ***
'******************************************************************************
'***    PROGRAMMEUR:                                                                              ***
'***      Royer Jean-Laurent                                                                         ***
'******************************************************************************

'******************************************************************************
'***    MODIF :                                                                                            ***
'******************************************************************************
Option Explicit

'******************************************************************************
'***    Declaration De Variable Public                                                          ***
'******************************************************************************

'******************************************************************************
'***    Declaration De Variable Public                                                          ***
'******************************************************************************
Private ObjControl As Object

'******************************************************************************
'***    Declaration D'Evenement Privée                                                        ***
'******************************************************************************

'******************************************************************************
'***    EVENEMENT:                                                                                    ***
'******************************************************************************
'***    FONCTION:                                                                                       ***
'******************************************************************************
'***    ENTREE:                                                                                          ***
'***    SORTIE:                                                                                           ***
'******************************************************************************
Private Sub Form_Load()
   Dim StrArg() As String

   On Error GoTo Err_Form_Load

   Select Case IsNull(Me.OpenArgs)
      Case True

         Set TxtNotesTraitements = TxtNotes

      Case False

         StrArg = Split(Me.OpenArgs, ":")

         Select Case StrArg(2)
            Case vbNullString

               Set ObjControl = Forms(StrArg(0)).Controls(StrArg(1))

            Case Else

               Set ObjControl = Forms(StrArg(0)).Controls(StrArg(1)).Form.Controls(StrArg(2))

         End Select

         TxtNotes = ObjControl

   End Select

Exit_Form_Load:

   Exit Sub

Err_Form_Load:

   MsgBox Err.Number & " " & Err.Description, , "Form_Load"

   Resume Exit_Form_Load
End Sub

'******************************************************************************
'***    EVENEMENT:                                                                                    ***
'******************************************************************************
'***    FONCTION:                                                                                       ***
'******************************************************************************
'***    ENTREE:                                                                                          ***
'***    SORTIE:                                                                                           ***
'******************************************************************************
Private Sub Form_Unload(Cancel As Integer)

   On Error GoTo Err_Form_Unload

   Select Case IsNull(Me.OpenArgs)
      Case True

         Set TxtNotesTraitements = Nothing

      Case False

         ObjControl = TxtNotes

   End Select

Exit_Form_Unload:

   Exit Sub

Err_Form_Unload:

   MsgBox Err.Number & " " & Err.Description, , "Form_Unload"

   Resume Exit_Form_Unload
End Sub
